version: "3"
services:
  asm_unicom:
    container_name: asm_unicom
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/AutoSignMachine #同步脚本地址
      - ./.temp/:/root/.AutoSignMachine #缓存文件地址
    restart: always
    tty: true
    network_mode: "bridge"
    hostname: asm_unicom
    environment:
      - enable_unicom=true #签到开关 false / true
      - config_unicom=/AutoSignMachine/default.json # 输入用户手机号
      - sckey= #输入用户密码
      - log_name=asm_unicom

